In [1]:
import pandas as pd
import numpy as np

In [2]:
file_path = "CH2O_09337_DFRS_DS95_2021_272_00_57/calibrated/ch2o_frs_calibrated_01_21272001904.csv"

df = pd.read_csv(file_path, header=None)

df.columns = [
    "Day",
    "Time",
    "Frequency",
    "Value_1",
    "Value_2",
    "Signal"
]

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [3]:
df.head()

        Day        Time     Frequency       Value_1       Value_2     Signal
0  2021-272  1144.00000  2.240000e+09  2.239989e+09  2.239989e+09  17.477752
1  2021-272  1144.08192  2.240000e+09  2.239989e+09  2.239989e+09  17.492057
2  2021-272  1144.16384  2.240000e+09  2.239989e+09  2.239989e+09  17.385770
3  2021-272  1144.24576  2.240000e+09  2.239989e+09  2.239989e+09  17.296193
4  2021-272  1144.32768  2.240000e+09  2.239989e+09  2.239989e+09  17.574878

In [4]:
print("Rows, Columns:")
print(df.shape)

Rows, Columns:
(12451, 6)

In [5]:
print("Columns:")
print(df.columns)

Columns:
Index(['Day', 'Time', 'Frequency', 'Value_1', 'Value_2', 'Signal'], dtype='object')

In [6]:
print("Data Types:")
print(df.dtypes)

Data Types:
Day           object
Time         float64
Frequency    float64
Value_1      float64
Value_2      float64
Signal       float64
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12451 entries, 0 to 12450
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Day        12451 non-null  object
 1   Time       12451 non-null  float64
 2   Frequency  12451 non-null  float64
 3   Value_1    12451 non-null  float64
 4   Value_2    12451 non-null  float64
 5   Signal     12451 non-null  float64
dtypes: float64(5), object(1)
memory usage: 583.8+ KB

In [8]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Day          0
Time         0
Frequency    0
Value_1      0
Value_2      0
Signal       0
dtype: int64

In [9]:
df.describe()

               Time     Frequency       Value_1       Value_2         Signal
count  12451.000000  1.245100e+04  1.245100e+04  1.245100e+04   12451.000000
mean    1653.951987  2.240000e+09  2.239991e+09  2.239989e+09    2446.950192
std      294.456389  0.000000e+00  2.208886e+04  3.749467e+02   22053.561235
min     1144.000000  2.240000e+09  2.239917e+09  2.239988e+09  -72847.760333
25%     1398.975994  2.240000e+09  2.239988e+09  2.239988e+09      43.900761
50%     1653.951987  2.240000e+09  2.239989e+09  2.239989e+09      47.116694
75%     1908.927981  2.240000e+09  2.239989e+09  2.239989e+09      47.715035
max     2163.903974  2.240000e+09  2.240200e+09  2.239990e+09  211780.448691

In [10]:
print("Unique Days:")
print(df["Day"].unique())

Unique Days:
['2021-272']

In [11]:
print("Minimum Signal:", df["Signal"].min())
print("Maximum Signal:", df["Signal"].max())
print("Average Signal:", df["Signal"].mean())

Minimum Signal: -72847.760333
Maximum Signal: 211780.448691
Average Signal: 2446.950191739137

In [12]:
print("Minimum Frequency:", df["Frequency"].min())
print("Maximum Frequency:", df["Frequency"].max())

Minimum Frequency: 2240000000.0
Maximum Frequency: 2240000000.0

In [13]:
df.to_csv(
    "clean_dfsar_data.csv",
    index=False
)

print("Clean dataset saved successfully")

Clean dataset saved successfully